apiVersion: v1
kind: ConfigMap
metadata:
  name: video-slicer-config
  namespace: video-slicer
data:
  APP_NAME: "VideoSlicer"
  APP_VERSION: "1.0.0"
  DEBUG: "False"
  OLLAMA_MODEL: "llama3"
  MAX_FILE_SIZE: "5368709120"
  UPLOAD_DIR: "./uploads"